name: main
on:
  - pull_request
  - push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --check && cargo clippy --all-targets --all-features
      - run: cargo check --all-features
      - run: cargo test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-tarpaulin && cargo tarpaulin --out xml
      - uses: codecov/codecov-action@v4
